name: Generate Releases HTML

on:
  push:
    branches: [ web ]
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get releases and generate HTML
        run: |
          echo "<!DOCTYPE html><html><head><title>Releases</title></head><body><h1>Releases</h1><ul>" > releases.html
          curl -s "https://api.github.com/repos/${{ github.repository }}/releases" | 
          jq -r '.[] | "<li><a href=\"\(.html_url)\">\(.tag_name): \(.name)</a> (\(.published_at | sub("T.*Z"; ""))) - Assets: " + (.assets | map("<a href=\"\(.browser_download_url)\">\(.name)</a>") | join(", ")) + "</li>"' >> releases.html
          echo "</ul></body></html>" >> releases.html
      
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add releases.html
          git commit -m "Update releases.html" || exit 0
          git push
